# nginx webserver running on CentOS 7
# Requires vbguest due guest additions to not included in official box
# vagrant plugin install vagrant-vbguest

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "nginx.ws"
  config.vm.network "private_network", type: "dhcp"
  config.ssh.insert_key = false

# sync local vagrant directory to nginx root, install and enable nginx
  config.vm.synced_folder ".", "/usr/share/nginx/html", type: "virtualbox"
  config.vm.provision "shell",
    inline: "yum install nginx && chkconfig nginx on"

# set virtualbox options
  config.vm.provider "virtualbox" do |v|
    v.name = "nginx.ws"
    v.customize [
      "modifyvm", :id,
      "--cpuexecutioncap", "25",
      "--memory", "256",
    ]
  end
end